project:
  type: website
  preview:
    port: 3000
    browser: false
    watch-inputs: true


website:
  title: "Part II Computational Physics"
  page-navigation: true
  sidebar:
    # contents: auto
    contents:
      - section: "Notes"
        contents:
          - index.qmd
          - notes/intro.qmd
          - notes/getting-going.qmd
          - notes/numpy.qmd
          - notes/numbers.qmd
          - notes/ode.qmd
          - notes/monte-carlo.qmd
          # - notes/complexity.qmd
          # # - notes/fourier.qmd
          # # - notes/linear.qmd
          # # - notes/divide.qmd
          # # - notes/dynamic.qmd
          # # - notes/autograd.qmd
          - notes/references.qmd

      - section: "Slides"
        contents:
          - slides/getting-going.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
  # pdf:
  #   documentclass: scrreprt

execute:
  freeze: auto  # re-render only when source changes

