editor:
  render-on-save: true

project:
  type: website
  preview:
    port: 3000
    browser: false
    watch-inputs: true


website:
  title: "Part II Computational Physics"
  page-navigation: true
  sidebar:
    # contents: auto
    collapse-level: -1
    style: floating
    contents:
      - section: "Notes"
        contents:
          - index.qmd
          - notes/intro.qmd
          - notes/getting-going.qmd
          - notes/numpy.qmd
          - notes/numbers.qmd
          - notes/ode.qmd
          - notes/monte-carlo.qmd
          - notes/complexity.qmd
          - notes/fourier.qmd
          - notes/autodiff.qmd
          - notes/linear.qmd

      - section: "Slides"
        contents:
          - slides/getting-going.qmd
          - slides/numpy.qmd
          - slides/numbers-and-odes.qmd
          - slides/monte-carlo.qmd
          - slides/complexity.qmd
          - slides/fourier.qmd
          - slides/autodiff.qmd
          - slides/linear.qmd

      - section: "Exercises and Projects"
        contents:
          - exercises/exercises.qmd
          - exercises/projects.qmd

bibliography: references.bib
number-sections: true

format:
  html:
    theme: cosmo
    toc: true

  # pdf:
  #   documentclass: scrreprt

execute:
  freeze: auto  # re-render only when source changes

