# Introduction


Computation is important for experimental physicists for analysing data. For theoretical physics, computation is used to deal with the awkward fact that physical theories are _generally not tractable_. You can't solve Maxwell's equations, the Navier–Stokes equation, or Schrödinger's equation in any but the simplest situations. 

To be blunt, this means that your knowledge of physics, while very nice, is of _no use whatsoever_ unless you can write a program to solve more complicated problems. Sorry.

It's important to understand that this need to apply our mathematical descriptions of nature in more general settings was the principal driving force behind the invention of the computer.

More than this,

Church Turing hypothesis

Turing's cathedral

Books

Part IB notes are very good

Garth Wells

https://github.com/CambridgeEngineering/PartIA-Computing-Michaelmas/

Rougier

https://www.labri.fr/perso/nrougier/from-python-to-numpy/
https://github.com/rougier/scientific-visualization-book