---
title: Exercises
draft: false
---

There are __four computing exercises__ to be completed in the last four weeks of full Lent term; one per week. The exercises count for 0.2 units or further work, or roughly 2% of your final mark for the year. Thus each exercise should only take you a few hours. Each of the four exercises is marked out of 5 for a total of 20 marks. Marks will be awarded in proportion to the amount of each exercise you successfully complete. _Successfully complete_ means that at the very least the relevant code should run!

- __First exercise__: Friday 20th February – Friday 27th February
- __Second exercise__: Friday 27th February – Friday 6th March
- __Third exercise__: Friday 6th March – Friday 13th March
- __Fourth exercise__: Friday 13th March – Friday 20th March (last day of full Lent term)

You will receive a link to the exercise via email on the first day before noon (i.e. Friday 20th February for the first exercise). The deadline for every exercise is __12 noon__ on the final day (i.e. Friday 27th February for the first exercise).

# How to submit

You will be using [GitHub classroom](https://classroom.github.com/) to submit your work, so you will need a GitHub account if you don't already have one. If you've never used GitHub before, you can try out the [starter course](https://classroom.github.com/a/kRglu3Oa). There's a bit of jargon to learn to get going ("repos", "forks" and so on), but it's not that bad.

The following instructions contain lots of __bold__ and _italics_ that have accumulated over several years trying to get students to follow them. Sorry. 

- Each week I will email you a link to a new exercise. The first time you click on one of the classroom links you will be asked to pick your identifier (CRSid) in order to join the classroom. Let me know if your id is missing. __Please make sure you click the right CRSid!__ If you click someone else's they won't be able to get theirs and I will have to manually reassign them 😡.

- Once you accept the assignment, GitHub will create a repository called `<exercise-name>-<your-username>` in the [Part-II-Computational-Physics](https://github.com/Part-II-Computational-Physics) organization on GitHub. This repository will contain the exercise description. Please __change the name of the repo to `<exercise-name>-<CRSid>`__ for ease of marking. Only you and the course admins (the demonstrators and me) can see this repo. _You will use this repo to submit your work_. __Do not make ("fork") another repo__ outside the organization and work in that. I won't be able to see it. 

- (__Important__) _There is no explicit "submit" button_. You submit your work by making changes ("commits") to the repository _on GitHub_ (if you make commits to a copy of the repository on your computer, you must "push" them to GitHub). You can make as many commits as you like up until the deadline. Note that you can continue to add commits to the repo after the deadline, but only the last commit before the deadline is counted as the submission.

- If you can see your work on GitHub (in a repo in the [Part-II-Computational-Physics](https://github.com/Part-II-Computational-Physics) organization), then I can. __Do not email me to ask whether I can see your work__.

 - The policy on late submission of coursework is described in the [Physics course handbook](https://universityofcambridgecloud.sharepoint.com/sites/PHY_INT_UG/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPHY%5FINT%5FUG%2FShared%20Documents%2FCurrent%20undergraduates%2FHandbook%2FPhysics%5FCourse%5FHandbook%5F2025%5F2026%20v2%2Epdf&parent=%2Fsites%2FPHY%5FINT%5FUG%2FShared%20Documents%2FCurrent%20undergraduates%2FHandbook) (Section 7). Note in particular that applications for extensions should be made by submitting [this form](https://forms.office.com/pages/responsepage.aspx?id=RQSlSfq9eUut41R7TzmG6Y64hS-YY0NHhP2hmw9lbpdUNFdLU01PRTFXVURORUhBVllUS0QwSkxBRS4u&route=shorturl), not by contacting me directly. __Late submissions should be made by committing to GitHub in the usual way__. They should NOT be sent to the undergraduate office (despite what it says on the form). __The deadline for late submissions is seven days after the original deadline i.e. 12 noon__.

Ok, yelling over. Please use the [discussions](https://github.com/orgs/Part-II-Computational-Physics/discussions) section to ask questions to your demonstrators (about the exercises) and me (about everything else). Treat the discussions as if they are a real life examples class where others can learn from your questions and the answers to them.

<!-- If you're using VS Code, there is a [GitHub Classroom extension](https://marketplace.visualstudio.com/items?itemName=GitHub.classroom) that allows you to view, work on, and submit assignments directly within the editor. -->

# The exercises

## First exercise: PDEs

[The first exercise](https://classroom.github.com/a/Rfpx6VIj) concerns solving a simple PDE using different methods. Your demonstrator for this exercise is Arshad Kamal. The deadline is __12 noon__ on Friday 27th February.

## Second exercise: Monte Carlo

[The second exercise](https://classroom.github.com/a/vhDAeJQi) is about Monte Carlo techniques applied to the Ising model. You demonstrator is Bogdan Rajkov. The deadline is __12 noon__ on Friday 6th March.



## Third exercise: automatic differentiation

[The third exercise](https://classroom.github.com/a/9WKeJCx7) is about using automatic differentiation to train a simple neural network. Your demonstrator is Thorbjørn Clausen. The deadline is __12 noon__ on Friday 13th March.

## Fourth exercise: exact diagonalization

[The fourth exercise](https://classroom.github.com/a/jNcuMJnP) is about using some of the linear algebra techniques from the [linear algebra lecture](../notes/linear.qmd) to study spin chains. Your demonstrator is Vedant Motamarri. The deadline is __12 noon__ on Friday 20th March.
 


